[tool.poetry]
name = "cardboard"
version = "0.1.0"
description = "A dashboard for managing puzzles and tracking status during a puzzle hunt."
authors = ["Cardinality Puzzlers <cardinalitypuzzles@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "*"
python-dotenv = "*"
django-heroku = "*"
google-api-python-client = "*"
social-auth-app-django = "*"
django-taggit = "*"
url-normalize = "*"
gunicorn = "*"
djangorestframework = "*"
disco-py = ">=0.0.14rc1"
celery = "*"
django-celery-results = "*"
redis = "*"
"discord.py" = "*"

[tool.poetry.dev-dependencies]
pre-commit = "*"
black = "*"
coverage = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
